language: python

sudo: false

python:
  - '2.7'
  - '3.5'
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pytest-cov pytest coveralls
  - pip install -e .

script:
  - pytest --cov=pshtt
  - flake8 .
  - coveralls
